name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Yeh branch trigger karega jab push ho
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build project
        run: |
          npm install  # agar aapne npm use kiya hai toh
          npm run build  # agar koi build script hai toh
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Yahan wo folder likhen jahan se aapka built project hai
